"""
Project state: the locked master references (STEP 5 of the workflow doc).

Once an asset is generated it is written here and never regenerated by a
plain run -- only `--force` on a specific step overwrites it. This is what
enforces the doc's rule: "Nunca substitua o personagem ou ambiente travado
por uma nova geracao, a menos que explicitamente instruido."
"""

import json
import os
from dataclasses import asdict, dataclass, field
from typing import Dict, Optional

from . import config


@dataclass
class Asset:
    url: str
    local_path: str


@dataclass
class ProjectState:
    character_reference: Optional[Asset] = None
    location_reference: Optional[Asset] = None
    character_sheet: Optional[Asset] = None
    location_sheet: Optional[Asset] = None
    shots: Dict[str, Asset] = field(default_factory=dict)

    def to_json(self) -> dict:
        return asdict(self)

    @staticmethod
    def from_json(d: dict) -> "ProjectState":
        def asset_or_none(v):
            return Asset(**v) if v else None

        return ProjectState(
            character_reference=asset_or_none(d.get("character_reference")),
            location_reference=asset_or_none(d.get("location_reference")),
            character_sheet=asset_or_none(d.get("character_sheet")),
            location_sheet=asset_or_none(d.get("location_sheet")),
            shots={k: Asset(**v) for k, v in d.get("shots", {}).items()},
        )


def load_state() -> ProjectState:
    if os.path.exists(config.STATE_FILE):
        with open(config.STATE_FILE, "r", encoding="utf-8") as f:
            return ProjectState.from_json(json.load(f))
    return ProjectState()


def save_state(state: ProjectState) -> None:
    os.makedirs(config.OUTPUT_DIR, exist_ok=True)
    with open(config.STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(state.to_json(), f, indent=2, ensure_ascii=False)
